// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uolnwtafpmbgdfxuabad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbG53dGFmcG1iZ2RmeHVhYmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzA1NTMsImV4cCI6MjA2MzY0NjU1M30.Q6uzo8h6Nb55KI1OUG-RWa54JuShc0mIDkowf__pjdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);